List<String> audioDataSource = [
  'assets/audios/01Virtues_of_Ramadan_20230318_061558 (1).mp3',
  'assets/audios/1Devotion_From_the_life.opus',
  'assets/audios/1. Some Basic Rules on Ibaadah.mp3',
  'assets/audios/001_Meaning_of_fitan_types_of_fitan_and_how_dangerous_a_fitan_could.amr'
      'assets/audios/001 Seeroh Aaisha_intro.amr',
  'assets/audios/001 Hajj Rite_045004.amr',
  'assets/audios/001 Explaining the Quran - Reading the Quran.amr',
  'assets/audios/001 - Muqaddimah_Risalah_Al-Qayrawaniy.amr',
  'assets/audios/سيرة_عائشة_أم_المؤمنين_من_سير_أعلام_النبلاء.opus',
  'assetsaudios/سورة النساء ٤٤-٤٦.m4a',
  'assets/audios/سورة النساء ٤٤-٤٥.m4a',
  'assets/audios/سورة النساء ٤٣.m4a',
  'assets/audios/سورة النساء ٣٩-٤٠.amr',
  'assets/audios/سورة النساء ٣٨.amr',
  'assets/audiosسورة النساء ٣٧.amr',
  'assets/audios/سورة النساء ٣٥-٣٦.amr',
  'assets/audios/سورة النساء ٣٤.amr',
  'assets/audios/سورة النساء ٣٤ (ج).amr',
  'assets/audios/سورة النساء ٣٤ (ب).amr',
  'assets/audios/سورة النساء ٣٢.amr',
  'assets/audios/سورة النساء ٣١-٣٢.amr',
  'assets/audios/سورة النساء ٢٩.amr',
  'assets/audios/سورة النساء ٢٩ (ب).amr',
  'assets/audios/سورة النساء ٢٦-٢٨.amr',
  'assets/audios/سورة النساء ٢٢-٢٣.amr',
  'assets/audios/سورة النساء ٢٢-٢٣ (1).amr',
  'assets/audios/سورة النساء ٢٠.amr',
  'assets/audios/سورة النساء ٢٠ (1).amr',
  'assets/audios/سورة النساء ١٩.amr',
  'assets/audios/سورة النساء ١٨.amr',
  'assets/audios/سورة النساء ١٧.amr',
  'assets/audios/سورة الرعد ٤٢-٤٣.amr',
  'assets/audios/سورة الرعد ٣٩-٤١.amr',
  'assets/audios/سورة الرعد ٣٨-٣٩.amr',
  'assets/audios/سورة الرعد ٣٧.amr',
  'assets/audios/سورة الرعد ٣٥-٣٧.amr',
  'assets/audios/سورة الرعد ٣١-٣٤.amr',
  'assets/audios/سورة الرعد ٢٧-٣٠.amr',
  'assets/audios/سورة الرعد ٢٢-٢٦.amr',
  'assets/audios/سورة الرعد ٢٠-٢٢.amr',
  'assets/audios/سورة الرعد ١٨-١٩.amr',
  'assets/audios/سورة الرعد ١٤-١٧.amr',
  'assets/audios/سورة الرعد ١٢-١٥.amr',
  'assets/audios/سورة الرعد ٩-١٢.amr',
  'assets/audios/سورة الرعد ٨.amr',
  'assets/audios/سورة الرعد ٨ (1).amr',
  'assetsaudios/سورة الرعد ٧-٨.amr',
  'assets/audios/سورة الرعد ٥-٦.amr',
  'assets/audios/سورة الرعد ٣-٤.amr',
  'assets/audios/سورة الرعد ٢.amr',
  'assets/audios/سورة الرعد ١.amr',
  'assets/audio/سورة الرعد ١ (1).amr',
  'assets/audios/سورة إبراهيم ١٨-٢٣.amr',
  'assets/audios/سورة إبراهيم ٨-١٧.amr',
  'assets/audios/سورة إبراهيم ٥-٨.amr',
  'assets/audios/سورة إبراهيم ٤.amr',
  'assets/audios/سورة إبراهيم ١-٣.amr',
  'assets/audios/سورة آل عمران ١٩٠-١٩١.amr',
  'assets/audios/سورة آل عمران ١٨٧.amr',
  'assets/audios/سورة آل عمران ١٢-١٥.amr',
  'assets/audios/سورة آل عمران ١٢-١٥ (1).amr',
  'assets/audios/رياض الصالحين حديث ١٠٦٤-١٠٦٥.m4a',
  'assets/audios/رياض الصالحين حديث ١٠٦١-١٠٦٣.m4a',
  'assets/audios/رياض الصالحين حديث ١٠٥٣-١٠٦٠.m4a',
  'assets/audios/رياض الصالحين حديث ١٠٤٧-١٠٥٢.amr',
  'assets/audios/رياض الصالحين حديث ١٠٤٥-١٠٤٦.amr',
  'assets/audios/رياض الصالحين حديث ١٠٤٢-١٠٤٤.amr',
  'assets/audios/رياض الصالحين حديث ١٠٣٧.amr',
  'assets/audios/ رياض الصالحين حديث ١٠٣٤.amr',
  'assets/audios/رياض الصالحين حديث ١٠٣٤-١٠٣٦.amr',
  'assets/audios/رياض الصالحين حديث ١٠٣٤-١٠٣٦ (1).amr',
  'assets/audios/رياض الصالحين حديث ١٠٢٤.amr',
  'assets/audios/رياض الصالحين حديث ١٠٢٣.amr',
  'assets/audios/رياض الصالحين باب فضل الوضوء.amr',
  'assets/audios/تزكية النف.m4a',
  'assets/audios/النهي عن الشرك.m4a',
  'assets/audios/أهمية_المساجد_ودورها_في_المجتمع_الإسلامي.amr',
  'assets/audios/women and aids.amr',
  'assets/audios/Who is Allah - Dr. sharafuddeen Gbadebo Raji - 16-Jul-2023.amr',
  'assets/audios/What_next_after_Ramadan_Dr_Sharafudeen_Raaji_22_May_2022.amr',
  'assets/audios/Ways To Safeguard Eemaan - Dr Sharafuddeen - 01-Oct-22.mp3',
  'assets/audios/Virtues_of_nawafil_Lecture2_Abu_Naasir.opus',
  'assets/audios/Ustadh_Ibrahim_Abu_Naasir_Virtues_of_Islam_10_April_21_English_DN.amr',
  'assets/audios/Understand_the_Quran_Dr_Sharafuddeen_Raji_04_Aug_2023_mp3.amr',
  'assets/audios/trusting somebody does not mean not accounting.amr',
  'assets/audios/The_Time_of_Temptation_and_Muslim_Stance_in_it_Dr_Sharafudeen_Raaji.mp3',
  'assets/audios/The_Obligation_to_follow_the_Sunnah_of_the_Prophet_Dr_sharafuddeen.amr',
  'assets/audios/The_Honor_of_Prophet_Muhammad_ﷺ_Dr_Sharafudeen_Raaji_20_May_2022.amr',
  'assets/audios/THE ROLE OF MUSLIMS IN REFORMING THR SOCIETY.mp3',
  'assets/audios/The Hour Draws Near-Tribulation of The Last Hour.mp3',
  'assets/audios/The Hour Draws Near-Tribulation of The Last Hour (Q&A).mp3',
  'assetsaudios/the heedlessness of man(A sign of the last hour).opus',
  'assets/audios/The Evil Effects of Sins 2.amr',
  'assets/audios/The Evil Effects of Sins 1.amr',
  'assets/audios/سورة النساء ٣٩-٤٠.amr',
  'assets/audios/سورة النساء ٣٨.amr',
  'assets/audiosسورة النساء ٣٧.amr',
  'assets/audios/سورة النساء ٣٥-٣٦.amr',
  'assets/audios/سورة النساء ٣٤.amr',
  'assets/audios/سورة النساء ٣٤ (ج).amr',
  'assets/audios/سورة النساء ٣٤ (ب).amr',
  'assets/audios/سورة النساء ٣٢.amr',
  'assets/audios/سورة النساء ٣١-٣٢.amr',
  'assets/audios/سورة النساء ٢٩.amr',
  'assets/audios/سورة النساء ٢٩ (ب).amr',
  'assets/audios/سورة النساء ٢٦-٢٨.amr',
  'assets/audios/سورة النساء ٢٢-٢٣.amr',
  'assets/audios/سورة النساء ٢٢-٢٣ (1).amr',
  'assets/audios/سورة النساء ٢٠.amr',
  'assets/audios/سورة النساء ٢٠ (1).amr',
  'assets/audios/سورة النساء ١٩.amr',
  'assets/audios/سورة النساء ١٨.amr',
  'assets/audios/سورة النساء ١٧.amr',
  'assets/audios/سورة الرعد ٤٢-٤٣.amr',
  'assets/audios/سورة الرعد ٣٩-٤١.amr',
  'assets/audios/سورة الرعد ٣٨-٣٩.amr',
  'assets/audios/سورة الرعد ٣٧.amr',
  'assets/audios/سورة الرعد ٣٥-٣٧.amr',
  'assets/audios/سورة الرعد ٣١-٣٤.amr',
  'assets/audios/سورة الرعد ٢٧-٣٠.amr',
  'assets/audios/سورة الرعد ٢٢-٢٦.amr',
  'assets/audios/سورة الرعد ٢٠-٢٢.amr',
  'assets/audios/سورة الرعد ١٨-١٩.amr',
  'assets/audios/سورة الرعد ١٤-١٧.amr',
  'assets/audios/سورة الرعد ١٢-١٥.amr',
  'assets/audios/سورة الرعد ٩-١٢.amr',
  'assets/audios/سورة الرعد ٨.amr',
  'assets/audios/سورة الرعد ٨ (1).amr',
  'assetsaudios/سورة الرعد ٧-٨.amr',
  'assets/audios/سورة الرعد ٥-٦.amr',
  'assets/audios/سورة الرعد ٣-٤.amr',
  'assets/audios/سورة الرعد ٢.amr',
  'assets/audios/سورة الرعد ١.amr',
  'assets/audio/سورة الرعد ١ (1).amr',
  'assets/audios/سورة إبراهيم ١٨-٢٣.amr',
  'assets/audios/سورة إبراهيم ٨-١٧.amr',
  'assets/audios/سورة إبراهيم ٥-٨.amr',
  'assets/audios/سورة إبراهيم ٤.amr',
  'assets/audios/سورة إبراهيم ١-٣.amr',
  'assets/audios/سورة آل عمران ١٩٠-١٩١.amr',
  'assets/audios/سورة آل عمران ١٨٧.amr',
  'assets/audios/سورة آل عمران ١٢-١٥.amr',
  'assets/audios/سورة آل عمران ١٢-١٥ (1).amr',
  'assets/audios/رياض الصالحين حديث ١٠٦٤-١٠٦٥.m4a',
  'assets/audios/رياض الصالحين حديث ١٠٦١-١٠٦٣.m4a',
  'assets/audios/رياض الصالحين حديث ١٠٥٣-١٠٦٠.m4a',
  'assets/audios/رياض الصالحين حديث ١٠٤٧-١٠٥٢.amr',
  'assets/audios/رياض الصالحين حديث ١٠٤٥-١٠٤٦.amr',
  'assets/audios/رياض الصالحين حديث ١٠٤٢-١٠٤٤.amr',
  'assets/audios/رياض الصالحين حديث ١٠٣٧.amr',
  'assets/audios/ رياض الصالحين حديث ١٠٣٤.amr',
  'assets/audios/رياض الصالحين حديث ١٠٣٤-١٠٣٦.amr',
  'assets/audios/رياض الصالحين حديث ١٠٣٤-١٠٣٦ (1).amr',
  'assets/audios/رياض الصالحين حديث ١٠٢٤.amr',
  'assets/audios/رياض الصالحين حديث ١٠٢٣.amr',
  'assets/audios/رياض الصالحين باب فضل الوضوء.amr',
  'assets/audios/تزكية النف.m4a',
  'assets/audios/النهي عن الشرك.m4a',
  'assets/audios/أهمية_المساجد_ودورها_في_المجتمع_الإسلامي.amr',
  'assets/audios/women and aids.amr',
  'assets/audios/Who is Allah - Dr. sharafuddeen Gbadebo Raji - 16-Jul-2023.amr',
  'assets/audios/What_next_after_Ramadan_Dr_Sharafudeen_Raaji_22_May_2022.amr',
  'assets/audios/Ways To Safeguard Eemaan - Dr Sharafuddeen - 01-Oct-22.mp3',
  'assets/audios/Virtues_of_nawafil_Lecture2_Abu_Naasir.opus',
  'assets/audios/Ustadh_Ibrahim_Abu_Naasir_Virtues_of_Islam_10_April_21_English_DN.amr',
  'assets/audios/Understand_the_Quran_Dr_Sharafuddeen_Raji_04_Aug_2023_mp3.amr',
  'assets/audios/trusting somebody does not mean not accounting.amr',
  'assets/audios/The_Time_of_Temptation_and_Muslim_Stance_in_it_Dr_Sharafudeen_Raaji.mp3',
  'assets/audios/The_Obligation_to_follow_the_Sunnah_of_the_Prophet_Dr_sharafuddeen.amr',
  'assets/audios/The_Honor_of_Prophet_Muhammad_ﷺ_Dr_Sharafudeen_Raaji_20_May_2022.amr',
  'assets/audios/THE ROLE OF MUSLIMS IN REFORMING THR SOCIETY.mp3',
  'assets/audios/The Hour Draws Near-Tribulation of The Last Hour.mp3',
  'assets/audios/The Hour Draws Near-Tribulation of The Last Hour (Q&A).mp3',
  'assetsaudios/the heedlessness of man(A sign of the last hour).opus',
  'assets/audios/The Evil Effects of Sins 2.amr',
  'assets/audios/The Evil Effects of Sins 1.amr',
];
